---
title       : Economic Data Explorer
subtitle    : JHU's Coursera Developing Data Products Course Project
author      : mattmdedek
job         : 
framework   : revealjs     # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
ext_widgets : {rCharts: libraries/nvd3}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
--- #Slide1

<style>iframe{background-color: white}</style>

## Coursera: Johns Hopkins University

#### Data Science Specialization

#### Developing Data Products Course Project

## Political and Budgetary Data Explorer

--- #Slide2

## Are Political Stereotypes Hype or Truth?

#### The commonly held beleifs are that:

* Republicans tax less and spend less
* Democrats tax more and spend more


Does the data show this relationship between the size of government and the political parties in power?

--- #Slide3

## The Application

This data product lets you explore US Federal budget data
in the context of the political party majorities in congress and
the oval office.

### Sources of Data

* Political Party Data: Wikipedia
http://en.wikipedia.org/wiki/Party_divisions_of_United_States_Congresses

* Budget Data: Office of Management and Budget
http://www.whitehouse.gov/omb/budget/Historicals

--- #Slide4

## Features

#### Choose variables to compare, view annual details

```{r simple-plot, comment = NA, message = F, echo = F, results = 'asis'}
require(knitr)
require(reshape2)
require(rCharts)

df <- read.table("assets/demo-data/mergedData.txt", sep="\t", header=T)

# Create the main plot
tmpP<-nPlot(FedExpGDP ~ Year, data=df, type="scatterChart", group='PresParty')
tmpP$chart(color=c('Blue', 'Red'))

# label the axes
tmpP$xAxis(axisLabel = "Year")
tmpP$yAxis(axisLabel = "Federal Gov't Expeditures as % of GDP")

# Generate a tooltip on hover which displays
# color coded information of the president, house and senate.
tmpP$chart(tooltipContent="#!
        function(key, x, y, e){
          tt = '<strong>' + e.point.Year + '</strong><br/>';
          tt = tt + 'President: <font color=\"';
          if(e.point.PresParty == 'Democrat') {
            tt = tt + 'blue';
          } else {
            tt = tt + 'red';
          }
          tt = tt + '\">' + e.point.President + '</font>';
          tt = tt + '<br />House: <font color=\"red\">' + e.point.HouseRepublicans + '</font> / ';
          tt = tt + '<font color=\"blue\">' + e.point.HouseDemocrats + '</font>';
          tt = tt + '<br />Senate: <font color=\"red\">' + e.point.SenRepublicans + '</font> / ';
          tt = tt + '<font color=\"blue\">' + e.point.SenDemocrats + '</font>';
          return tt;
        } !#")

# attach the plot
# tmpP$addParams(width=600, height=400)
tmpP

```

--- #Slide5

## Thanks for Viewing My App

Application URL:
https://mattmdedek.shinyapps.io/JHU-DataProductsProject/

Application Source Code:
https://github.com/mattmdedek/jhu-data-products/tree/master

Slides Source Code:
https://github.com/mattmdedek/jhu-data-products/tree/gh-pages

